src/cl-jupyter.asd
src/iopub.lisp
src/kernel.lisp
src/message.lisp
src/shell.lisp
src/stdin.lisp

Hi,
I saw the commits in project https://github.com/fredokun/cl-jupyter adding message encryption (see https://github.com/fredokun/cl-jupyter/commit/4141a0ade52fbac3858a54a6fcfb2210a916e844 and https://github.com/fredokun/cl-jupyter/commit/510aea192b2347d7393e8857a9e30bba6b875a31) and since i needed it for the maxima-jupyter kernel, i tried to apply the same changes in this project. Also added the `key` in `defun send-input-request`.
I was able to build the core image and put it to work with the current stable version of jupyterhub 0.2.0.
However, i'm a programmer but not a LISP or Maxima programmer (as a matter of fact, i do not know a single line of LISP...). So i ask you to verify the changes and see if they make sense to you.
I still have a problem dealing with inputs like "integrate …

Message encryption.

---

src/display.lisp
src/packages.lisp
src/utils.lisp

Allow PDF to be returned from `plot2d`. Along with mpastell/Pweave#104 this allows Maxima graphs to appear in Pweave.

Add PDF rendering

---

src/display.lisp
src/packages.lisp

This PR removes the need to quote `plot2d` and adds support for other plot commands. There are still some issues left to be resolved as detailed below. Current usage is:
```
set_plot_option([svg_file, "foo.svg"]);
plot2d (sin(x), [x, -%pi, %pi]);
plot3d (u^2 - v^2, [u, -2, 2], [v, -3, 3], [grid, 100, 100],[mesh_lines_color,false]);
```

Allow plots without quote mechanism

---

make-maxima-jupyter-recipe.txt
src/evaluator.lisp
src/shell.lisp

This PR removes dependence on `parse_string` and uses `mread-noprompt` to behave more like a Maxima notebook/prompt, i.e. allowing multiple terminated commands in an execute request. The results are then passed back each in a `execute_result` message.
This also makes it possible to write complete Maxima scripts in Pweave document. In other words, the following will work and not just execute the first command only.
```latex
%!TeX pweaveKernel=maxima
\documentclass{article}
\begin{document}
Solve an equation and make a graph!
<<fig = True>>=
solve(x^3+2);
set_plot_option([pdf_file, "foo.pdf"])$
plot3d (u^2 - v^2, [u, -2, 2], [v, -3, 3], [grid, 100, 100], [mesh_lines_color,false]);
@
\end{document}
```
Since there are some significant changes here, more testing is probably needed before …

Allow multiple input lines in execute request

---

src/display.lisp

This PR makes `plot-p` a little more stringent to avoid tests on arrays of two symbols, etc.

Make plot-p more stringent

---

src/packages.lisp
src/shell.lisp
src/utils.lisp

This PR adds support for the `is_complete_request` and the `shutdown_request` messages. It also cleans up `handle-execute-request` and `handle-kernel-info-request` a bit.

Add support for is_complete_request and shutdown_request

---

src/evaluator.lisp
src/iopub.lisp
src/kernel.lisp
src/message.lisp
src/shell.lisp
src/stdin.lisp
src/user.lisp

This PR improves messaging a bit, captures Maxima errors and makes `quit` work.
- Store identities in message to avoid passing to every function.
- Remove buffer parameters since this is not part the Jupyter protocol and is not used anywhere.
- Only return `message` from `wire-deserialize`,
- Check signatures on received messages.
- Capture Maxima errors as conditions and send appropriate error message replies.
- Convert quit requests to a condition and capture using same mechanism.

Improve messaging and capture Maxima errors

---

install-maxima-jupyter.py
src/additions.lisp
src/kernel.lisp
src/maxima-jupyter.asd
src/packages.lisp
src/results.lisp

This PR uses `jupyter_` as a prefix for all Maxima visible functions and `jupyter-` for Lisp visible functions in the `maxima` namespace. I put all of these functions into `additions.lisp`. If you like that structure we could move all the overridden Maxima functions into `overrides.lisp` along with some comments of why they had to be overridden to make things work.

Use consistent naming of functions in maxima namespace

---

src/evaluator.lisp
src/iopub.lisp
src/kernel.lisp
src/overrides-cl-info.lisp
src/overrides.lisp
src/results.lisp
src/stdin.lisp
tests/client.py

This PR adds support for a STDIN channel stream that overrides `*query-io*` and `*standard-input*`. This makes it possible to detect input requests without overriding the internals of Maxima functions like `retrieve`. It also adds the beginning of a testing framework for the client side. Some unneeded functions are removed and all Maxima overrides are moved into `overrides.lisp`.
The class `stdin-stream` looks for `finish-output` calls on `*query-io*` and interprets them as printed prompts which are used in an `input_request`. The read side of `*query-io*` then filled with the results. The `iopub-stream` assists by looking for ANSI SOS and ANSI ST which are used as prompt delimeters. It writes prompts to `*query-io*` causing an `input_request`. All read calls from `*standard-input*`, …

Add automatic prompt detection and testing

---

src/overrides.lisp
src/results.lisp

This PR has some small tweaks for displaying Maxima expressions. `*display-labels-p*` is now respected when rendering LaTeX. LaTeX is also not generated for input labels. This makes the output from `example` more usable.

Display Tweaks

---

Dockerfile
Readme.md
docker-install-quicklisp.lisp

This PR adds support for mybinder.org and local usage of repo2docker along with some basic Docker instructions should someone want to build their own image.
I've reworked the README a bit with some instructions, which could probably be expanded a bit. Please note that the binder badge will not work until this PR is merged. Until then https://mybinder.org/v2/gh/yitzchak/maxima-jupyter/binder will start a binder on this branch.
This resolves #9 and #43.
Thanks to @alessandro-dibella-rockalltech and @psychemedia for your work. It helped out a lot!

Add support for binder, repo2docker and Docker

---

install-maxima-jupyter.py

Fix permissions of kernel directory otherwise when installing
the files system-wise (as root) the normal users cannot access to
the maxima kernel file. Cleaned also the temporary files used
during installation.

fix permissions of installed files

---

src/overrides.lisp

Fixes #53.
Please note that inline math markers are inserted manually.

Add override for print

---

src/kernel.lisp

Some small updates for common-lisp-jupyter
- Add `package` slot to avoid calling `find-package` repeatedly.
- Add `inform` function to replace `info` with logging levels and logging sources.
This PR should fix #59.

Updates for Quicklisp 2019-05-21

---

Dockerfile
Readme.md

I've introduced some cleanup that does two things:
1. reduces the number of container layers
1. removes the package cache from the guest file system
Both of these reduce the overall image size.
Additionally, I've changed the image to use `ENTRYPOINT`, making the default usage simpler as well as reducing the number of commands necessary for running `jupyter` in other modes (`ENTRYPOINT` essentially lets you treat your Docker container like your executable). I've updated the README to provide clarity around this.
Finally, two other bits have been provided outside of this repo, for the benefit of users:
* a pre-built Docker image is available [here](https://hub.docker.com/r/calyau/maxima-jupyter) for users who don't/can't have a local copy of maxima-jupyter on their machines
* a handful of …

Dockerfile tweaks

---

maxima.js
src/overrides-cl-info.lisp

Hi Robert,
here's the proposed fix for issue [#68](https://github.com/robert-dodier/maxima-jupyter/issues/68):
Maxima Syntax Highlighting hangs when '$' is entered.
WetHat

Fixed issue #68: Maxima Syntax Highlighting hangs when '$' is entered.

---

Readme.md

Hello,
The Readme instructs to place maxima_lexer.py to the Pygments installation directory. However with this the error `nbconvert failed: No module named 'pygments.lexers.maxima_lexer'` is encountered when trying to exports notebooks to HTML format.
I think the correct directory is the `lexers` directory, and I corrected this to the instructions.
Thank you for the project!

Fix instructed directory for maxima_lexer.py

---

Dockerfile

Glibc patch link seems broken, and after removing no problems were
identified. It seems maxima-sbcl is needed to make use of sbcl
quicklisp libs.

Remove glibc patch, install sbcl maxima backend

---

src/overrides.lisp
src/results.lisp

Some of the demos need to be updated because contourplot and others have been deprecated. This just fixes logic for the changes in return format of plot2d.
Fixes #118

Updates for changes in plot2d return format

---

Dockerfile.debian

A  Dockerfile based on Debian, building maxima from source, installing up-to-date node, install jupyter with pip
It has the following advantages:
1. Debian in not a rolling distribution, so it  a more stable base to build the docker file on. I found the Arch-based file would sometimes not build due to recent changes to the distro.
2. Multi-stage build means that the build dependencies are not all included in the run-time system
3. Recent, fixed version of node installed with nvm
4. Pip-installed recent jupyter
5. Maxima built from source
6. Final image is significantly smaller -- I find 1GB vs 3GB for the Arch based image

Debian-based docker file building maxima from source
